<a href="https://colab.research.google.com/github/KrishnaGande/Ineuron-Learning/blob/main/Numpy_in_details.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Array

In [ ]:
import numpy as np
np.array(["vbhvh", 2, 3])

array(['vbhvh', '2', '3'], dtype='<U5')

In [ ]:
[1,2,3,4,'krish','sjankla']

[1, 2, 3, 4, 'krish', 'sjankla']

In [ ]:
np.array([1,2,3,4,'krish','sjankla'])

array(['1', '2', '3', '4', 'krish', 'sjankla'], dtype='<U21')

In [ ]:
#Upcasting:

In [ ]:
np.array([1, 2, 3.0])

array([1., 2., 3.])

In [ ]:
#two dimensions

In [ ]:
 np.array([[1, 2], [3, 4]],ndmin=6)

array([[[[[[1, 2],
           [3, 4]]]]]])

In [ ]:
#Minimum dimensions 2:

In [ ]:
np.array([1, 2, 3], ndmin=5)

array([[[[[1, 2, 3]]]]])

In [ ]:
#dtype

In [ ]:
 np.array([1, 2, 3], dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [ ]:
#Data-type consisting of more than one element:

In [ ]:
np.array([(1,2),(3,4)])

array([[1, 2],
       [3, 4]])

In [ ]:
x = np.array([(1,2),(3,4)],dtype=[('a','<i2'),('b','<i8')])
x

array([(1, 2), (3, 4)], dtype=[('a', '<i2'), ('b', '<i8')])

In [ ]:
type(x[0][1])

numpy.int64

In [ ]:
x[0][1]

2

In [ ]:
#Creating an array from sub-classes:

In [ ]:
np.mat(np.array([[1, 2],[4,7]]))

matrix([[1, 2],
        [4, 7]])

In [ ]:
type(np.mat([[1,3],[2,4]]))

numpy.matrix

In [ ]:
np.mat('1 2; 3 4')

matrix([[1, 2],
        [3, 4]])

In [ ]:
np.mat([[1,2],[5,6,8]])

/usr/local/lib/python3.7/dist-packages/numpy/matrixlib/defmatrix.py:145: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  arr = N.array(data, dtype=dtype, copy=copy)


matrix([[list([1, 2]), list([5, 6, 8])]], dtype=object)

# numpy.asarray

In [ ]:
#Convert the input to an array.

In [ ]:
#Convert a list into an array:

In [ ]:
 a = [[1, 2],[3,4]]
type(a)
np.asarray(a)

array([[1, 2],
       [3, 4]])

In [ ]:
type(np.asarray(a))

numpy.ndarray

In [ ]:
a = np.array([1, 2]) #Existing arrays are not copied
type(a)

numpy.ndarray

In [ ]:
np.asarray((1,2))

array([1, 2])

In [ ]:
#If dtype is set, array is copied only if dtype does not match:

In [ ]:
a = np.array([1, 2], dtype=np.float32)
a

array([1., 2.], dtype=float32)

In [ ]:
np.asarray([1,2]) is a

False

In [ ]:
np.asarray([1,2])

array([1, 2])

In [ ]:
np.asarray(a, dtype=np.float64) is a

False

In [ ]:
# ndarray subclasses are not passed through

In [ ]:
issubclass(np.matrix, np.ndarray)

True

In [ ]:
a = np.matrix([[1, 2]])
type(np.asanyarray(a))


numpy.matrix

In [ ]:
np.asarray(a)

array([[1, 2]])

In [ ]:
np.asanyarray(a)

matrix([[1, 2]])

In [ ]:
np.asarray(a)

array([[1, 2]])

# numpy.asanyarray

In [ ]:
a = [1, 2]
np.asanyarray(a)

array([1, 2])

In [ ]:
a = np.matrix([1, 2])
a

matrix([[1, 2]])

In [ ]:
np.asanyarray([1,2]) is a

False

#numpy.copy

In [ ]:
np.array(a, copy=True)  

array([[1, 2]])

In [ ]:
#Create an array x, with a reference y and a copy z:

In [ ]:
x = np.array([1, 2, 3])
x

array([1, 2, 3])

In [ ]:
#swallow copy : dependant variable
y = x
y

array([1, 2, 3])

In [ ]:
y[1]=3367484

In [ ]:
y

array([      1, 3367484,       3])

In [ ]:
x

array([      1, 3367484,       3])

In [ ]:
x[0]=45

In [ ]:
y

array([     45, 3367484,       3])

In [ ]:
x

array([     45, 3367484,       3])

In [ ]:
z[0]=98
z

NameError: ignored

In [ ]:
#deep copy : variable is independant of primary variable 
z = np.copy(x)
z

array([     45, 3367484,       3])

In [ ]:
y[0] = 100
x

In [ ]:
x

In [ ]:
id(x[0])

In [ ]:
id(y[0])

In [ ]:
id(x) 

In [ ]:
id(y)

# numpy.fromfunction

In [ ]:
#Construct an array by executing a function over each coordinate.

In [ ]:
np.fromfunction(lambda i, j: i == j, (3, 3), dtype=int)

In [ ]:
np.fromfunction(lambda i, j, k, l: i * j * k * l, (2, 3, 3, 3), dtype=int)

In [ ]:
#Create a new 1-dimensional array from an iterable object.

In [ ]:
iterable = (x*x for x in range(5))
iterable

In [ ]:
np.fromiter(iterable, float)

In [ ]:
#A new 1-D array initialized from text data in a string

In [ ]:
a = np.fromstring('234 234',sep=' ')
a

In [ ]:
np.fromstring('1, 2', dtype=int, sep=',')

In [ ]:
# How to create create a record array from a (flat) list of arrays

In [ ]:
x1=np.array([1,2,3,4])

In [ ]:
x2=np.array(['a','dd','xyz','12'])

In [ ]:
x3=np.array([1.1,2,3,4])
x4=np.array([1.1,2,3,4])
type(x4)

In [ ]:
r = np.core.records.fromarrays([x1,x2,x3,x4],names='a,b,c,d')
r

In [ ]:
print(r[1]["b"])

x1[1]=34

In [ ]:
x1[1]

# data types

In [ ]:
my_list = [1,2,3]
import numpy as np
arr = np.array(my_list)
print("Type/Class of this object:",type(arr))
print("Here is the vector\n--------------------\n",arr)

In [ ]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
mat = np.array(my_mat)
print("Type/Class of this object:",type(mat))
print("Here is the matrix\n----------\n",mat,"\n----------")
print("Dimension of this matrix: ",mat.ndim,sep='') #ndim gives the dimensison, 2 for a matrix, 1 for a vector
print("Size of this matrix: ", mat.size,sep='') #size gives the total number of elements
print("Shape of this matrix: ", mat.shape,sep='') #shape gives the number of elements along each axes (dimension)
print("Data type of this matrix: ", mat.dtype,sep='') #dtype gives the data type contained in the array


In [ ]:
my_mat = [[1.1,2,3],[4,5,6],[7,8.3,9]]
mat = np.array(my_mat)
print(mat)
print("Data type of the modified matrix: ", mat.dtype,sep='') #dtype gives the data type contained in the array
print("\n\nEven tuples can be converted to ndarrays...")


In [ ]:
b = np.array([(1.5,2,3), (4,5,6)])
print("We write b = np.array([(1.5,2,3), (4,5,6)])")
print("Matrix made from tuples, not lists\n---------------------------------------")
print(b)

# arange and linspace

In [ ]:
np.arange(16.5,5,-2)

In [ ]:
print("A series of numbers:",type(np.arange(5,16)))
np.arange(5,16,2.3)# A series of numbers from low to high

In [ ]:
list(range(5,16,2))

In [ ]:
list(range(50,-1,5))

In [ ]:
print("Numbers spaced apart by 2:",np.arange(50,-1,5)) # Numbers spaced apart by 2

In [ ]:
print("Numbers spaced apart by float:",np.arange(0,11,2.5)) # Numbers spaced apart by 2.5

In [ ]:
print("Every 5th number from 50 in reverse order\n",np.arange(5.0,-1,-5))

In [ ]:
print("21 linearly spaced numbers between 1 and 5\n--------------------------------------------")
print((np.linspace(1,5,50)))

# Matrix creation

In [ ]:
print("Vector of zeroes\n---------------------")
print(np.zeros(5))

Vector of zeroes
---------------------
[0. 0. 0. 0. 0.]


In [ ]:
print("Matrix of zeroes\n--------------------")
print(np.zeros((3,4,2))) # Notice Tuples

Matrix of zeroes
--------------------
[[[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]]


In [ ]:
print("Vector of ones\n---------------------")
print(np.ones(5))

Vector of ones
---------------------
[1. 1. 1. 1. 1.]


In [ ]:
print("Matrix of ones\n---------------------")
print(np.ones((5,2,8))) # Note matrix dimension specified by Tuples


Matrix of ones
---------------------
[[[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]]


In [ ]:
print("Matrix of 5's\n---------------------")
print(5+np.ones((3,5)))

Matrix of 5's
---------------------
[[6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]]


In [ ]:
print("Empty matrix\n-------------\n", np.empty((4,5),dtype=int))

Empty matrix
-------------
 [[94284937053120              0              0              0
               0]
 [             0              0              0              0
               0]
 [             0              0              0              0
               0]
 [             0              0              0              0
               0]]


In [ ]:
mat1 = np.eye(4) 
print("Identity matrix of dimension", mat1.shape)
print(mat1)

Identity matrix of dimension (4, 4)
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
np.arange(3)

array([0, 1, 2])

In [ ]:
np.arange(3.0)

array([0., 1., 2.])

In [ ]:
 np.arange(3,7)

array([3, 4, 5, 6])

In [ ]:
np.arange(3,7,2)

array([3, 5])

In [ ]:
np.linspace(2.0, 3.0, num=5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [ ]:
np.linspace(2.0, 3.0, num=5, endpoint=False)

array([2. , 2.2, 2.4, 2.6, 2.8])

In [ ]:
np.linspace(2.0, 3.0, num=9, retstep=True)

(array([2.   , 2.125, 2.25 , 2.375, 2.5  , 2.625, 2.75 , 2.875, 3.   ]), 0.125)

In [ ]:
#Return numbers spaced evenly on a log scale.
np.linspace(2.0, 3.0, num=4)

array([2.        , 2.33333333, 2.66666667, 3.        ])

In [ ]:
np.logspace(2.0, 3.0, num=4,base = 2)

array([4.        , 5.0396842 , 6.34960421, 8.        ])

In [ ]:
np.logspace(2.0, 3.0, num=4, endpoint=False)

array([100.        , 177.827941  , 316.22776602, 562.34132519])

In [ ]:
np.logspace(2.0, 3.0, num=4, base=2.0)

array([4.        , 5.0396842 , 6.34960421, 8.        ])

In [ ]:
(np.zeros((3,4,8)) + 5)*2

array([[[10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.]],

       [[10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.]],

       [[10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.]]])

In [ ]:
np.linspace(4,8,80)

array([4.        , 4.05063291, 4.10126582, 4.15189873, 4.20253165,
       4.25316456, 4.30379747, 4.35443038, 4.40506329, 4.4556962 ,
       4.50632911, 4.55696203, 4.60759494, 4.65822785, 4.70886076,
       4.75949367, 4.81012658, 4.86075949, 4.91139241, 4.96202532,
       5.01265823, 5.06329114, 5.11392405, 5.16455696, 5.21518987,
       5.26582278, 5.3164557 , 5.36708861, 5.41772152, 5.46835443,
       5.51898734, 5.56962025, 5.62025316, 5.67088608, 5.72151899,
       5.7721519 , 5.82278481, 5.87341772, 5.92405063, 5.97468354,
       6.02531646, 6.07594937, 6.12658228, 6.17721519, 6.2278481 ,
       6.27848101, 6.32911392, 6.37974684, 6.43037975, 6.48101266,
       6.53164557, 6.58227848, 6.63291139, 6.6835443 , 6.73417722,
       6.78481013, 6.83544304, 6.88607595, 6.93670886, 6.98734177,
       7.03797468, 7.08860759, 7.13924051, 7.18987342, 7.24050633,
       7.29113924, 7.34177215, 7.39240506, 7.44303797, 7.49367089,
       7.5443038 , 7.59493671, 7.64556962, 7.69620253, 7.74683

In [ ]:
np.mat([1,2,3,4])

matrix([[1, 2, 3, 4]])

In [ ]:
np.shape(np.ones((4,5,2)))

(4, 5, 2)

In [ ]:
np.ndim(np.ones((4,5,2)))

3

In [ ]:
type(np.ones((4,5,2)))

numpy.ndarray

In [ ]:
x1=np.zeros((3,3,3))
x2=np.ones((3,3,3))

In [ ]:
x1

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [ ]:
x1+x2

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [ ]:
#Extract a diagonal or construct a diagonal array.

In [ ]:
np.arange(16).reshape(-1,8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [ ]:
x = np.arange(16).reshape((-1,4))

In [ ]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
np.diag(x)

array([ 0,  5, 10, 15])

In [ ]:
np.diag(x, k=1)

array([ 1,  6, 11])

In [ ]:
np.diag(x, k=-1)

array([ 4,  9, 14])

In [ ]:
np.diag(np.diag(x))

array([[ 0,  0,  0,  0],
       [ 0,  5,  0,  0],
       [ 0,  0, 10,  0],
       [ 0,  0,  0, 15]])

In [ ]:
#Create a two-dimensional array with the flattened input as a diagonal.

In [ ]:
np.diagflat([[1,2], [3,4]],2)

array([[0, 0, 1, 0, 0, 0],
       [0, 0, 0, 2, 0, 0],
       [0, 0, 0, 0, 3, 0],
       [0, 0, 0, 0, 0, 4],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [ ]:
np.diagflat([1,2], 1)

array([[0, 1, 0],
       [0, 0, 2],
       [0, 0, 0]])

In [ ]:
#An array with ones at and below the given diagonal and zeros elsewhere.

In [ ]:
np.tri(3, 3,0)

array([[1., 0., 0.],
       [1., 1., 0.],
       [1., 1., 1.]])

In [ ]:
np.tri(3, 5,k=-1)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.]])

In [ ]:
#return a Lower triangle of an array.

In [ ]:
np.tril([[1,2,3],[4,5,6],[7,8,9]], 0)

array([[1, 0, 0],
       [4, 5, 0],
       [7, 8, 9]])

In [ ]:
#return Upper triangle of an array.

In [ ]:
np.triu([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], 2)

array([[0, 0, 3],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

# Random number generation

In [ ]:
print("Random number generation (from Uniform distribution)")
print(np.random.rand(2,3)) # 2 by 3 matrix with random numbers ranging from 0 to 1, Note no Tuple is necessary 

Random number generation (from Uniform distribution)
[[0.87281628 0.25524145 0.42870993]
 [0.73170781 0.44902786 0.52894835]]


In [ ]:
print("Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal")
print(np.random.randn(4,3))

Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal
[[ 1.38160257 -1.03843956 -1.12495004]
 [-0.11090035  0.67199881  1.32563441]
 [ 0.34836958 -0.81244004  0.62005855]
 [ 1.28275894  1.26055861 -0.51539694]]


In [ ]:
print("Random integer vector:\n",np.random.randint(1,10,(4,4))) #randint (low, high, # of samples to be drawn)
print ("\nRandom integer matrix")


Random integer vector:
 [[6 6 4 1]
 [2 1 7 7]
 [5 2 2 4]
 [2 5 7 5]]

Random integer matrix


In [ ]:
print(np.random.randint(1,100,(4,4,5))) #randint (low, high, # of samples to be drawn in a tuple to form a matrix)
print("\n20 samples drawn from a dice throw:",np.random.randint(1,7,20)) # 20 samples drawn from a dice throw

[[[57  9 72 54 86]
  [86 49 97 40 57]
  [73 26 83 29 92]
  [93 16 21 34 53]]

 [[50 81 81 93 51]
  [70 94 56 64 85]
  [47 42 32 79 16]
  [33 27  2 10 52]]

 [[51 41 91  4 17]
  [59 82 98 82 96]
  [85 63 13  7 43]
  [19 56 92 86 38]]

 [[88 75  1 72 16]
  [72 99 73 56 49]
  [47 76 88 61 11]
  [46 43 10 60 46]]]

20 samples drawn from a dice throw: [1 6 6 6 6 4 2 5 2 5 5 5 2 1 6 2 3 4 4 2]


# Reshaping

In [ ]:
a.reshape(2,3,5)

array([[[54, 94, 94, 22, 71],
        [19, 69, 10, 15, 50],
        [22, 66, 45, 86, 43]],

       [[23, 19, 60,  6, 27],
        [99, 62, 30, 97, 76],
        [98, 19, 80, 50, 11]]])

In [ ]:
a.reshape(6,-19878)

array([[54, 94, 94, 22, 71],
       [19, 69, 10, 15, 50],
       [22, 66, 45, 86, 43],
       [23, 19, 60,  6, 27],
       [99, 62, 30, 97, 76],
       [98, 19, 80, 50, 11]])

In [ ]:
from numpy.random import randint as ri
a = ri(1,100,30)
b = a.reshape(2,3,5)
c = a.reshape(6,-19878)
c

array([[54, 94, 94, 22, 71],
       [19, 69, 10, 15, 50],
       [22, 66, 45, 86, 43],
       [23, 19, 60,  6, 27],
       [99, 62, 30, 97, 76],
       [98, 19, 80, 50, 11]])

In [ ]:
print ("Shape of a:", a.shape)
print ("Shape of b:", b.shape)
print ("Shape of c:", c.shape)


Shape of a: (30,)
Shape of b: (2, 3, 5)
Shape of c: (6, 5)


In [ ]:
print("\na looks like\n",'-'*20,"\n",a,"\n",'-'*20)
print("\nb looks like\n",'-'*20,"\n",b,"\n",'-'*20)
print("\nc looks like\n",'-'*20,"\n",c,"\n",'-'*20)



a looks like
 -------------------- 
 [54 94 94 22 71 19 69 10 15 50 22 66 45 86 43 23 19 60  6 27 99 62 30 97
 76 98 19 80 50 11] 
 --------------------

b looks like
 -------------------- 
 [[[54 94 94 22 71]
  [19 69 10 15 50]
  [22 66 45 86 43]]

 [[23 19 60  6 27]
  [99 62 30 97 76]
  [98 19 80 50 11]]] 
 --------------------

c looks like
 -------------------- 
 [[54 94 94 22 71]
 [19 69 10 15 50]
 [22 66 45 86 43]
 [23 19 60  6 27]
 [99 62 30 97 76]
 [98 19 80 50 11]] 
 --------------------


In [ ]:
A = ri(1,100,10) # Vector of random interegrs
print("\nVector of random integers\n",'-'*50,"\n",A)
print("\nHere is the sorted vector\n",'-'*50,"\n",np.sort(A))



Vector of random integers
 -------------------------------------------------- 
 [12 60 17 61 62  1 21 61 88 19]

Here is the sorted vector
 -------------------------------------------------- 
 [ 1 12 17 19 21 60 61 61 62 88]


In [ ]:
#M = ri(1,100,25).reshape(5,5) # Matrix of random interegrs
print(M)
#print("\nHere is the sorted matrix along each row\n",'-'*50,"\n",np.sort(M, kind='mergesort')) # Default axis =1
print("\nHere is the sorted matrix along each column\n",'-'*50,"\n",np.sort(M, axis=1,kind='mergesort'))

[[28 78 22 49 24]
 [85 78 43 63 55]
 [93 56 78 35 31]
 [ 2 79 52 72 18]
 [21 96 42 19 75]]

Here is the sorted matrix along each column
 -------------------------------------------------- 
 [[22 24 28 49 78]
 [43 55 63 78 85]
 [31 35 56 78 93]
 [ 2 18 52 72 79]
 [19 21 42 75 96]]


In [ ]:
print("Max of a:", M.max())
print("Max of b:", b.max())
b

Max of a: 96
Max of b: 99


array([[[54, 94, 94, 22, 71],
        [19, 69, 10, 15, 50],
        [22, 66, 45, 86, 43]],

       [[23, 19, 60,  6, 27],
        [99, 62, 30, 97, 76],
        [98, 19, 80, 50, 11]]])

In [ ]:
M

array([[28, 78, 22, 49, 24],
       [85, 78, 43, 63, 55],
       [93, 56, 78, 35, 31],
       [ 2, 79, 52, 72, 18],
       [21, 96, 42, 19, 75]])

In [ ]:
print("Max of a location:", M.argmax(axis= 1 ))
print("Max of b location:", b.argmax())
print("Max of c location:", b.argmax())

Max of a location: [1 0 0 1 1]
Max of b location: 20
Max of c location: 20


# Indexing and slicing

In [ ]:
arr = np.arange(0,11)
print("Array:",arr)


Array: [ 0  1  2  3  4  5  6  7  8  9 10]


In [ ]:
print("Element at 7th index is:", arr[7])


Element at 7th index is: 7


In [ ]:
print("Elements from 3rd to 5th index are:", arr[3:6:2])


Elements from 3rd to 5th index are: [3 5]


In [ ]:
print("Elements up to 4th index are:", arr[:4])
arr

Elements up to 4th index are: [0 1 2 3]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
print("Elements from last backwards are:", arr[-1:7:-1])


Elements from last backwards are: [10  9  8]


In [ ]:
print("3 Elements from last backwards are:", arr[-1:-5:2])


3 Elements from last backwards are: []


In [ ]:
arr = np.arange(0,21,2)
print("New array:",arr)


New array: [ 0  2  4  6  8 10 12 14 16 18 20]


In [ ]:
print("Elements at 2nd, 4th, and 9th index are:", arr[[2,4,9]]) # Pass a list as a index to subset

Elements at 2nd, 4th, and 9th index are: [ 4  8 18]


In [ ]:
import numpy as np 
mat = np.array(ri(10,100,45)).reshape(3,5,3)
print("Matrix of random 2-digit numbers\n--------------------------------\n",mat)
mat[1:4,3:5]
mat[0:3,[1,3]]

Matrix of random 2-digit numbers
--------------------------------
 [[[79 17 30]
  [18 72 29]
  [62 35 63]
  [71 66 81]
  [97 19 18]]

 [[65 96 35]
  [89 60 84]
  [41 10 45]
  [60 96 54]
  [94 98 27]]

 [[95 39 45]
  [55 96 36]
  [98 52 70]
  [78 66 29]
  [63 15 83]]]


array([[[18, 72, 29],
        [71, 66, 81]],

       [[89, 60, 84],
        [60, 96, 54]],

       [[55, 96, 36],
        [78, 66, 29]]])

In [ ]:
mat[0][0][1]

17

In [ ]:
for i in range(5):
  print(mat[0][i][1])

17
72
35
66
19


In [ ]:
mat[0:3,0:2]

array([[[79, 17, 30],
        [18, 72, 29]],

       [[65, 96, 35],
        [89, 60, 84]],

       [[95, 39, 45],
        [55, 96, 36]]])

In [ ]:
mat[0:3,[1,3]]

array([[[18, 72, 29],
        [71, 66, 81]],

       [[89, 60, 84],
        [60, 96, 54]],

       [[55, 96, 36],
        [78, 66, 29]]])

In [ ]:
print("\nDouble bracket indexing\n------------------------")
print("Element in row index 1 and column index 2:", mat[1][1])
mat


Double bracket indexing
------------------------
Element in row index 1 and column index 2: [89 60 84]


array([[[79, 17, 30],
        [18, 72, 29],
        [62, 35, 63],
        [71, 66, 81],
        [97, 19, 18]],

       [[65, 96, 35],
        [89, 60, 84],
        [41, 10, 45],
        [60, 96, 54],
        [94, 98, 27]],

       [[95, 39, 45],
        [55, 96, 36],
        [98, 52, 70],
        [78, 66, 29],
        [63, 15, 83]]])

In [ ]:
print("\nSingle bracket with comma indexing\n----------------------------------")
print("Element in row index 1 and column index 2:", mat[1,2])
print("\nRow or column extract\n----------------------")



Single bracket with comma indexing
----------------------------------
Element in row index 1 and column index 2: [41 10 45]

Row or column extract
----------------------


In [ ]:
print("Entire row at index 2:", mat[2])
print("Entire column at index 3:", mat[:,3])


Entire row at index 2: [[95 39 45]
 [55 96 36]
 [98 52 70]
 [78 66 29]
 [63 15 83]]
Entire column at index 3: [[71 66 81]
 [60 96 54]
 [78 66 29]]


In [ ]:
print("\nSubsetting sub-matrices\n--------------------------")
print("Matrix with row indices 1 and 2 and column indices 3 and 4\n", mat[1:3,3:5])



Subsetting sub-matrices
--------------------------
Matrix with row indices 1 and 2 and column indices 3 and 4
 [[[60 96 54]
  [94 98 27]]

 [[78 66 29]
  [63 15 83]]]


In [ ]:
print("Matrix with row indices 0 and 1 and column indices 1 and 3\n", mat[0:2,[1,3]])

Matrix with row indices 0 and 1 and column indices 1 and 3
 [[[18 72 29]
  [71 66 81]]

 [[89 60 84]
  [60 96 54]]]


# Subseting

In [ ]:
mat = np.array(ri(10,100,15)).reshape(3,5)
print("Matrix of random 2-digit numbers\n--------------------------------\n",mat)
mat>50

Matrix of random 2-digit numbers
--------------------------------
 [[11 76 63 35 15]
 [20 72 75 54 93]
 [48 51 89 84 58]]


array([[False,  True,  True, False, False],
       [False,  True,  True,  True,  True],
       [False,  True,  True,  True,  True]])

In [ ]:
print ("Elements greater than 50\n", mat[mat>50])

# Slicing

In [ ]:
mat = np.array([[11,12,13],[21,22,23],[31,32,33]])
print("Original matrix")
print(mat)


In [ ]:
mat_slice = mat[:2,:2]
print ("\nSliced matrix")
print(mat_slice)
print ("\nChange the sliced matrix")

In [ ]:
mat_slice[0,0] = 1000
print (mat_slice)

In [ ]:
print("\nBut the original matrix? WHOA! It got changed too!")
print(mat)


In [ ]:
# Little different way to create a copy of the slixed matrix
print ("\nDoing it again little differently now...\n")
mat = np.array([[11,12,13],[21,22,23],[31,32,33]])
print("Original matrix")
print(mat)


In [ ]:
mat_slice = np.array(mat[:2,:2]) # Notice the np.array command to create a new array not just slicing
print ("\nSliced matrix")
print(mat_slice)


In [ ]:
print ("\nChange the sliced matrix")
mat_slice[0,0] = 1000
print (mat_slice)


In [ ]:
print("\nBut the original matrix? NO CHANGE this time:)")
print(mat)

# Universal Functions

In [ ]:
mat1 = np.array(ri(1,10,9)).reshape(3,3)
mat2 = np.array(ri(1,10,9)).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n----------------------------------------\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n----------------------------------------\n",mat2)



1st Matrix of random single-digit numbers
----------------------------------------
 [[8 4 3]
 [9 5 1]
 [6 8 5]]

2nd Matrix of random single-digit numbers
----------------------------------------
 [[9 7 8]
 [1 3 8]
 [8 2 7]]


In [ ]:
mat1*mat2

array([[72, 28, 24],
       [ 9, 15,  8],
       [48, 16, 35]])

In [ ]:
mat1@mat2

array([[100,  74, 117],
       [ 94,  80, 119],
       [102,  76, 147]])

In [ ]:
#print("\nAddition\n------------------\n", mat1+mat2)
print("\nMultiplication\n------------------\n", mat1@mat2)



Multiplication
------------------
 [[100  74 117]
 [ 94  80 119]
 [102  76 147]]


In [ ]:
print("\nDivision\n------------------\n", mat1/0)
#print("\nLineaer combination: 3*A - 2*B\n-----------------------------\n", 3*mat1-2*mat2)



Division
------------------
 [[inf inf inf]
 [inf inf inf]
 [inf inf inf]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


In [ ]:
print("\nAddition of a scalar (100)\n-------------------------\n", 100+mat1)



Addition of a scalar (100)
-------------------------
 [[108 104 103]
 [109 105 101]
 [106 108 105]]


In [ ]:
print("\nExponentiation, matrix cubed here\n----------------------------------------\n", mat1**3)
print("\nExponentiation, sq-root using pow function\n-------------------------------------------\n",pow(mat1,3))


Exponentiation, matrix cubed here
----------------------------------------
 [[512  64  27]
 [729 125   1]
 [216 512 125]]

Exponentiation, sq-root using pow function
-------------------------------------------
 [[512  64  27]
 [729 125   1]
 [216 512 125]]


# Broadcasting

In [ ]:
#NumPy operations are usually done on pairs of arrays on an element-by-element basis. 
#In the simplest case, the two arrays must have exactly the same shape.
#NumPy’s broadcasting rule relaxes this constraint when the arrays’ shapes meet certain constraints. 
#When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing 
#dimensions, and works its way forward. Two dimensions are compatible when
#they are equal, or one of them is 1

In [ ]:
start = np.zeros((4,4))
start= start+100
start

array([[100., 100., 100., 100.],
       [100., 100., 100., 100.],
       [100., 100., 100., 100.],
       [100., 100., 100., 100.]])

In [ ]:
# create a rank 1 ndarray with 3 values
add_rows = np.array([1, 0, 2,5])
print(add_rows)

[1 0 2 5]


In [ ]:
y = start + add_rows  # add to each row of 'start' using broadcasting
print(y)

[[101. 100. 102. 105.]
 [101. 100. 102. 105.]
 [101. 100. 102. 105.]
 [101. 100. 102. 105.]]


In [ ]:
# create an ndarray which is 4 x 1 to broadcast across columns
add_cols = np.array([[0,1,2,3]])
add_cols = add_cols.T
print(add_cols)

[[0]
 [1]
 [2]
 [3]]


In [ ]:
# add to each column of 'start' using broadcasting
y = start + add_cols 
print(y)

[[100. 100. 100. 100.]
 [101. 101. 101. 101.]
 [102. 102. 102. 102.]
 [103. 103. 103. 103.]]


In [ ]:
# this will just broadcast in both dimensions
add_scalar = np.array([100])  
print(start+y)

[[200. 200. 200. 200.]
 [201. 201. 201. 201.]
 [202. 202. 202. 202.]
 [203. 203. 203. 203.]]


# Array Math

In [ ]:
mat1 = np.array(ri(1,10,9)).reshape(3,3)
mat2 = np.array(ri(1,10,9)).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n------------\n",mat2)



1st Matrix of random single-digit numbers

 [[4 1 8]
 [1 7 7]
 [7 3 1]]

2nd Matrix of random single-digit numbers
------------
 [[1 4 5]
 [8 2 8]
 [2 5 7]]


In [ ]:
print("\nSq-root of 1st matrix using np\n------------------\n", np.sqrt(mat1))



Sq-root of 1st matrix using np
------------------
 [[2.         1.         2.82842712]
 [1.         2.64575131 2.64575131]
 [2.64575131 1.73205081 1.        ]]


In [ ]:
print("\nExponential power of 1st matrix using np\n",'-'*50,"\n", np.exp(mat1))



Exponential power of 1st matrix using np
 -------------------------------------------------- 
 [[5.45981500e+01 2.71828183e+00 2.98095799e+03]
 [2.71828183e+00 1.09663316e+03 1.09663316e+03]
 [1.09663316e+03 2.00855369e+01 2.71828183e+00]]


In [ ]:
print("\n10-base logarithm on 1st matrix using np\n",'-'*50,"\n", np.log10(mat1))
print(mat1)
print(mat2)


10-base logarithm on 1st matrix using np
 -------------------------------------------------- 
 [[0.60205999 0.         0.90308999]
 [0.         0.84509804 0.84509804]
 [0.84509804 0.47712125 0.        ]]
[[4 1 8]
 [1 7 7]
 [7 3 1]]
[[1 4 5]
 [8 2 8]
 [2 5 7]]


In [ ]:
print("\nModulo reminder using np\n",'-'*50,"\n", np.fmod(mat1,mat2))
mat1%mat2


Modulo reminder using np
 -------------------------------------------------- 
 [[0 1 3]
 [1 1 7]
 [1 3 1]]


array([[0, 1, 3],
       [1, 1, 7],
       [1, 3, 1]])

In [ ]:
print("\nCombination of functions by shwoing exponetial decay of a sine wave\n",'-'*70)



Combination of functions by shwoing exponetial decay of a sine wave
 ----------------------------------------------------------------------


In [ ]:
A = np.linspace(0,12*np.pi,1001)


In [ ]:
A

array([ 0.        ,  0.03769911,  0.07539822, ..., 37.62371362,
       37.66141273, 37.69911184])